const IDENTIFIER = '[modal]';

export const OPEN_MODAL = `${IDENTIFIER}OPEN`;
export const OPEN_MODAL_FOR_UPDATE = `${IDENTIFIER}OPEN_FOR_UPDATE`;
export const CLOSE_MODAL = `${IDENTIFIER}CLOSE`;

export const ADD_CUSTOM_TAG = `${IDENTIFIER}ADD_CUSTOM_TAG`;
export const DELETE_CUSTOM_TAG = `${IDENTIFIER}DELETE_CUSTOM_TAG`;
