const IDENTIFIER = '[auth]';

export const USER_LOGIN_REQUEST = `${IDENTIFIER}USER_LOGIN_REQUEST`;
export const USER_LOGIN_SUCCESS = `${IDENTIFIER}USER_LOGIN_SUCCESS`;
export const USER_LOGIN_FAILED = `${IDENTIFIER}USER_LOGIN_FAILED`;

export const GOOGLE_LOGIN_REQUEST = `${IDENTIFIER}GOOGLE_LOGIN_REQUEST`;
export const GOOGLE_LOGIN_SUCCESS = `${IDENTIFIER}GOOGLE_LOGIN_SUCCESS`;
export const GOOGLE_LOGIN_FAILED = `${IDENTIFIER}GOOGLE_LOGIN_FAILED`;

export const GITHUB_LOGIN_REQUEST = `${IDENTIFIER}GITHUB_LOGIN_REQUEST`;
export const GITHUB_LOGIN_SUCCESS = `${IDENTIFIER}GITHUB_LOGIN_SUCCESS`;
export const GITHUB_LOGIN_FAILED = `${IDENTIFIER}GITHUB_LOGIN_FAILED`;

export const USER_LOGOUT_REQUEST = `${IDENTIFIER}USER_LOGOUT_REQUEST`;
export const USER_LOGOUT_SUCCESS = `${IDENTIFIER}USER_LOGOUT_SUCCESS`;
export const USER_LOGOUT_FAILED = `${IDENTIFIER}USER_LOGOUT_FAILED`;

export const USER_SIGNUP_REQUEST = `${IDENTIFIER}USER_SIGNUP_REQUEST`;
export const USER_SIGNUP_SUCCESS = `${IDENTIFIER}USER_SIGNUP_SUCCESS`;
export const USER_SIGNUP_FAILED = `${IDENTIFIER}USER_SIGNUP_FAILED`;
