const IDENTIFIER = '[auth]';

export const USER_LOGIN_REQUEST = `${IDENTIFIER}USER_LOGIN_REQUEST`;
export const USER_LOGIN_SUCCESS = `${IDENTIFIER}USER_LOGIN_SUCCESS`;
export const USER_LOGIN_FAILED = `${IDENTIFIER}USER_LOGIN_FAILED`;
