import { NOTES_COLORS } from './colors';
import { LOGIN_FORM_NAME } from './auth';
import { SIGNUP_FORM_NAME } from './auth';
import { HELMET_TITLE, CATEGORIES_COLLECTION, NOTES_COLLECTION } from './base';

export {
  NOTES_COLORS,
  LOGIN_FORM_NAME,
  HELMET_TITLE,
  SIGNUP_FORM_NAME,
  CATEGORIES_COLLECTION,
  NOTES_COLLECTION,
};
