const IDENTIFIER = '[notes]';

export const UPDATE_NOTE_REQUEST = `${IDENTIFIER}UPDATE_NOTE_REQUEST`;
export const UPDATE_NOTE_SUCCESS = `${IDENTIFIER}UPDATE_NOTE_SUCCESS`;
export const UPDATE_NOTE_FAILED = `${IDENTIFIER}UPDATE_NOTE_FAILED`;

export const GET_NOTE_REQUEST = `${IDENTIFIER}GET_NOTE_REQUEST`;
export const GET_NOTE_SUCCESS = `${IDENTIFIER}GET_NOTE_SUCCESS`;
export const GET_NOTE_FAILED = `${IDENTIFIER}GET_NOTE_FAILED`;

export const GET_NOTE_FOR_UPDATE_REQUEST = `${IDENTIFIER}GET_NOTE_FOR_UPDATE_REQUEST`;
export const GET_NOTE_FOR_UPDATE_SUCCESS = `${IDENTIFIER}GET_NOTE_FOR_UPDATE_SUCCESS`;
export const GET_NOTE_FOR_UPDATE_FAILED = `${IDENTIFIER}GET_NOTE_FOR_UPDATE_FAILED`;

export const ADD_NOTE_REQUEST = `${IDENTIFIER}ADD_NOTE_REQUEST`;
export const ADD_NOTE_SUCCESS = `${IDENTIFIER}ADD_NOTE_SUCCESS`;
export const ADD_NOTE_FAILED = `${IDENTIFIER}ADD_NOTE_FAILED`;

export const TOGGLE_NOTE_REQUEST = `${IDENTIFIER}TOGGLE_NOTE_REQUEST`;
export const TOGGLE_NOTE_SUCCESS = `${IDENTIFIER}TOGGLE_NOTE_SUCCESS`;
export const TOGGLE_NOTE_FAILED = `${IDENTIFIER}TOGGLE_NOTE_FAILED`;

export const DELETE_NOTE_REQUEST = `${IDENTIFIER}DELETE_NOTE_REQUEST`;
export const DELETE_NOTE_SUCCESS = `${IDENTIFIER}DELETE_NOTE_SUCCESS`;
export const DELETE_NOTE_FAILED = `${IDENTIFIER}DELETE_NOTE_FAILED`;

export const GET_ALL_NOTES_REQUEST = `${IDENTIFIER}GET_ALL_NOTES_REQUEST`;
export const GET_ALL_NOTES_SUCCESS = `${IDENTIFIER}GET_ALL_NOTES_SUCCESS`;
export const GET_ALL_NOTES_FAILED = `${IDENTIFIER}GET_ALL_NOTES_FAILED`;
