const IDENTIFIER = '[notes]';

export const GET_NOTES = `${IDENTIFIER}GET_NOTES`;
export const UPDATE_NOTE = `${IDENTIFIER}UPDATE_NOTE`;
export const DELETE_NOTE = `${IDENTIFIER}DELETE_NOTE`;

export const ADD_NOTE_REQUEST = `${IDENTIFIER}ADD_NOTE_REQUEST`;
export const ADD_NOTE_SUCCESS = `${IDENTIFIER}ADD_NOTE_SUCCESS`;
export const ADD_NOTE_FAILED = `${IDENTIFIER}ADD_NOTE_FAILED`;

export const TOGGLE_NOTE_REQUEST = `${IDENTIFIER}TOGGLE_NOTE_REQUEST`;
export const TOGGLE_NOTE_SUCCESS = `${IDENTIFIER}TOGGLE_NOTE_SUCCESS`;
export const TOGGLE_NOTE_FAILED = `${IDENTIFIER}TOGGLE_NOTE_FAILED`;

export const DELETE_NOTE_REQUEST = `${IDENTIFIER}DELETE_NOTE_REQUEST`;
export const DELETE_NOTE_SUCCESS = `${IDENTIFIER}DELETE_NOTE_SUCCESS`;
export const DELETE_NOTE_FAILED = `${IDENTIFIER}DELETE_NOTE_FAILED`;
