const IDENTIFIER = '[notes]';

export const GET_NOTES = `${IDENTIFIER}GET_NOTES`;
export const TOGGLE_NOTE = `${IDENTIFIER}TOGGLE_NOTE`;
export const ADD_NOTE = `${IDENTIFIER}ADD_NOTE`;
export const UPDATE_NOTE = `${IDENTIFIER}UPDATE_NOTE`;
export const DELETE_NOTE = `${IDENTIFIER}DELETE_NOTE`;
