const IDENTIFIER = '[categories]';

export const TOGGLE_CATEGORIES = `${IDENTIFIER}TOGGLE_CATEGORIES`;
export const ACTIVATE_CATEGORY = `${IDENTIFIER}ACTIVATE_CATEGORY`;
export const DELETE_CATEGORY = `${IDENTIFIER}DELETE_CATEGORY`;

export const ADD_CATEGORY = `${IDENTIFIER}ADD_CATEGORY`;
