const IDENTIFIER = '[categories]';

export const TOGGLE_CATEGORIES = `${IDENTIFIER}TOGGLE_CATEGORIES`;
export const ACTIVATE_CATEGORY = `${IDENTIFIER}ACTIVATE_CATEGORY`;
export const DELETE_CATEGORY = `${IDENTIFIER}DELETE_CATEGORY`;

export const ADD_CATEGORY = `${IDENTIFIER}ADD_CATEGORY`;

export const FETCH_CATEGORIES_REQUEST = `${IDENTIFIER}FETCH_CATEGORIES_REQUEST`;
export const FETCH_CATEGORIES_SUCCESS = `${IDENTIFIER}FETCH_CATEGORIES_SUCCESS`;
export const FETCH_CATEGORIES_FAILED = `${IDENTIFIER}FETCH_CATEGORIES_FAILED`;
