const IDENTIFIER = '[categories]';

export const TOGGLE_CATEGORIES = `${IDENTIFIER}TOGGLE_CATEGORIES`;
export const ACTIVATE_CATEGORY = `${IDENTIFIER}ACTIVATE_CATEGORY`;

export const ADD_CATEGORY_REQUEST = `${IDENTIFIER}ADD_CATEGORY_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${IDENTIFIER}ADD_CATEGORY_SUCCESS`;
export const ADD_CATEGORY_FAILED = `${IDENTIFIER}ADD_CATEGORY_FAILED`;

export const DELETE_CATEGORY_REQUEST = `${IDENTIFIER}DELETE_CATEGORY_REQUEST`;
export const DELETE_CATEGORY_SUCCESS = `${IDENTIFIER}DELETE_CATEGORY_SUCCESS`;
export const DELETE_CATEGORY_FAILED = `${IDENTIFIER}DELETE_CATEGORY_FAILED`;
